apiVersion: v1
kind: Namespace
metadata:
  name: civicrm-staging
  labels:
    environment: staging
    purpose: go-live-validation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-config
  namespace: civicrm-staging
data:
  ENVIRONMENT: "staging"
  LOG_LEVEL: "debug"
  DATABASE_HOST: "mariadb-staging"
  REDIS_HOST: "redis-staging"
  N8N_HOST: "n8n-staging"
  CIVICRM_BASE_URL: "https://staging.menschlichkeit.at"
  MONITORING_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-staging
  namespace: civicrm-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-staging
  template:
    metadata:
      labels:
        app: mariadb-staging
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: civicrm_staging
        - name: MYSQL_USER
          value: civicrm
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-staging-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-staging-pvc
  namespace: civicrm-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-staging
  namespace: civicrm-staging
spec:
  selector:
    app: mariadb-staging
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-staging
  namespace: civicrm-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-staging
  template:
    metadata:
      labels:
        app: redis-staging
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-staging
  namespace: civicrm-staging
spec:
  selector:
    app: redis-staging
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
