---
# Service Account für n8n
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-service-account
  namespace: n8n-prod
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: service-account
---
# Role für n8n - minimale Berechtigungen
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: n8n-role
  namespace: n8n-prod
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
# RoleBinding für n8n
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-role-binding
  namespace: n8n-prod
subjects:
- kind: ServiceAccount
  name: n8n-service-account
  namespace: n8n-prod
roleRef:
  kind: Role
  name: n8n-role
  apiGroup: rbac.authorization.k8s.io
---
# Service Account für Monitoring
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-service-account
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: service-account
---
# ClusterRole für Prometheus (Metriken sammeln)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
# ClusterRoleBinding für Prometheus
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: prometheus-service-account
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-cluster-role
  apiGroup: rbac.authorization.k8s.io
