name: ux-ci
on: [push, pull_request]

jobs:
  ux:
    runs-on: ubuntu-latest
    services:
      wp:
        image: wordpress:6.8-php8.3-apache
        env:
          WORDPRESS_DB_HOST: 127.0.0.1
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: root
          WORDPRESS_DB_NAME: wp
        ports:
          - 8080:80
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: { node-version: '20' }
    - run: npm ci
    - name: PHP Quality
      run: composer install --prefer-dist && composer run-code-quality
    - name: SCSS & JS Lint
      run: npm run lint
    - name: Cypress A11y
      run: npm run test:a11y -- --browser chrome
    - name: Playwright Visual Regression
      run: npm run test:visual
    - name: Lighthouse CI
      run: npm run ci:lh
    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with: { name: ux-reports, path: reports/* }
