# Secrets Template f端r SOPS-Verschl端sselung
# Diese Datei wird mit SOPS + age verschl端sselt und als production-secrets.enc.yaml gespeichert

# n8n Secrets
n8n:
  encryptionKey: "CHANGE_ME_n8n_encryption_key_32_chars"
  jwtSecret: "CHANGE_ME_jwt_secret_64_chars"

# Datenbank-Secrets
postgresql:
  rootPassword: "CHANGE_ME_postgresql_root_password"
  password: "CHANGE_ME_n8n_database_password"

redis:
  password: "CHANGE_ME_redis_password"

# MinIO Secrets
minio:
  rootPassword: "CHANGE_ME_minio_root_password"
  n8nAccessKey: "n8n-service-user"
  n8nSecretKey: "CHANGE_ME_n8n_minio_secret"
  backupAccessKey: "backup-service-user"
  backupSecretKey: "CHANGE_ME_backup_minio_secret"

# CiviCRM API Secrets
civicrm:
  apiKey: "CHANGE_ME_civicrm_api_key"
  siteKey: "CHANGE_ME_civicrm_site_key"
  baseUrl: "https://civicrm.menschlichkeit.at"

# Externe API Secrets
craftmypdf:
  apiKey: "CHANGE_ME_craftmypdf_api_key"

brevo:
  apiKey: "CHANGE_ME_brevo_api_key"
  smtpKey: "CHANGE_ME_brevo_smtp_key"

freefinance:
  apiKey: "CHANGE_ME_freefinance_api_key"

openai:
  apiKey: "CHANGE_ME_openai_api_key"

# Social Media API Secrets
meta:
  accessToken: "CHANGE_ME_meta_access_token"
  pageId: "CHANGE_ME_meta_page_id"

linkedin:
  accessToken: "CHANGE_ME_linkedin_access_token"
  companyId: "CHANGE_ME_linkedin_company_id"

# Community-Integration Secrets
nextcloud:
  apiUser: "n8n-automation"
  apiPassword: "CHANGE_ME_nextcloud_api_password"

telegram:
  botToken: "CHANGE_ME_telegram_bot_token"
  chatId: "CHANGE_ME_telegram_chat_id"

# Monitoring & Alerting Secrets
slack:
  webhookUrl: "CHANGE_ME_slack_webhook_url"

# AWS Backup Secrets (f端r Cross-Region-Replikation)
aws:
  accessKey: "CHANGE_ME_aws_access_key"
  secretKey: "CHANGE_ME_aws_secret_key"

# SSL/TLS Secrets
tls:
  cert: |
    -----BEGIN CERTIFICATE-----
    CHANGE_ME_TLS_CERTIFICATE
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    CHANGE_ME_TLS_PRIVATE_KEY
    -----END PRIVATE KEY-----
